TravisCI: Drop Homebrew and Catalina builds
- Bintray, the old hosting service for Homebrew bottles, has been
  discontinued.  Homebrew itself has switched hosting providers, and
  our old bottles used here have been lost.
- We do not need the Catalina build because we can use GitHub Actions
  for new macOS builds.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,119 +4,128 @@
 language: cpp
 os: osx
 
-_script: &script
-  script:
-  - |
-    # Problem: The latest versions of Homebrew don't support older versions of
-    #          OS X. This causes builds to fail.
-    # Problem: Updating Homebrew on the latest macOS images is slow and causes
-    #          builds to take ~4 minutes, which is 90% of the build time.
-    # Fix:     Download & install Homebrew bottles manually.
+# Problem: Bintray has been discontinued.
 
-    (
-    set -e
-    shopt -s nullglob
-
-    # Download Homebrew bottles.
-    for bottle in $BOTTLES; do
-      # if bottle=foo-1.2   then name=foo-1.2 and rebuild=
-      # if bottle=foo-1.2^3 then name=foo-1.2 and rebuild=.3
-      name=${bottle%^*}
-      rebuild=${bottle#$name}
-      rebuild=${rebuild:+.}${rebuild#^}
-
-      url=https://homebrew.bintray.com/bottles/$name.$BOTTLE_TAG.bottle$rebuild.tar.gz
-      echo "Downloading $url..."
-
-      mkdir -p ~/Cellar
-      curl -sS -L "$url" | gzip -d | tar x -C ~/Cellar
-    done
-
-    # We don't have linker flags appropriate for linking against ar archives
-    # at the moment. Ensure the dylibs are chosen by removing the archives.
-    find ~/Cellar -name '*.a' -delete 2>/dev/null
-
-    # Link Homebrew bottles into a "/usr/local"-like environment in the home
-    # directory because the real /usr/local is read-only.
-    for pkg in ~/Cellar/*; do
-      builtin pushd $pkg >/dev/null
-      mkdir -p ~/opt
-      ln -s * ~/opt/${pkg##*/}
-      builtin popd >/dev/null
-
-      builtin pushd $pkg/* >/dev/null
-      for config in $(find lib/cmake -type f 2>/dev/null); do
-        sed -i '' -e s-@@HOMEBREW_PREFIX@@-$HOME- $config
-      done
-      for f in $(find bin include lib share -type d 2>/dev/null); do
-        mkdir -p ~/"$f"
-      done
-      (
-        IFS='
-    '
-        for f in $(find bin include lib share -type f 2>/dev/null); do
-          ln -s "$f" ~/"$f"
-        done
-      )
-      for f in $(find bin include lib share -type l 2>/dev/null); do
-        cp "$f" ~/"$f"
-      done
-      builtin popd >/dev/null
-    done
-
-    # Configure dylib install names.
-    for dylib in $(find ~/Cellar -name '*.dylib' -type f 2>/dev/null); do
-      #otool -L $dylib
-      chmod +w $dylib
-      install_name_tool -id $dylib $dylib
-      for line in $(otool -L $dylib | grep @@HOMEBREW_PREFIX@@); do
-        link=$(echo $line | awk '{ print $1 }')
-        link=${link#@@HOMEBREW_PREFIX@@/}
-        install_name_tool -change @@HOMEBREW_PREFIX@@/$link ~/$link $dylib
-      done
-      for line in $(otool -L $dylib | grep @@HOMEBREW_CELLAR@@); do
-        link=$(echo $line | awk '{ print $1 }')
-        link=${link#@@HOMEBREW_CELLAR@@/}
-        install_name_tool -change @@HOMEBREW_CELLAR@@/$link ~/Cellar/$link $dylib
-      done
-      #otool -L $dylib
-    done
-
-    export PATH=~/bin:"$PATH"
-    export CFLAGS="-I$HOME/include $CFLAGS"
-    export CXXFLAGS="-I$HOME/include $CXXFLAGS"
-    export LDFLAGS="-L$HOME/lib $LDFLAGS"
-    export CMAKE_PREFIX_PATH=~/lib/cmake${CMAKE_PREFIX_PATH:+;}"$CMAKE_PREFIX_PATH"
-
-    mkdir build
-    builtin cd >/dev/null build
-    cmake .. -DCMAKE_BUILD_TYPE=Debug $CMAKE_OPTS
-    make -j `sysctl -n hw.ncpu`
-    ./units
-    )
+#_script: &script
+#  script:
+#  - |
+#    # Problem: The latest versions of Homebrew don't support older versions of
+#    #          OS X. This causes builds to fail.
+#    # Problem: Updating Homebrew on the latest macOS images is slow and causes
+#    #          builds to take ~4 minutes, which is 90% of the build time.
+#    # Fix:     Download & install Homebrew bottles manually.
+#
+#    (
+#    set -e
+#    shopt -s nullglob
+#
+#    # Download Homebrew bottles.
+#    for bottle in $BOTTLES; do
+#      # if bottle=foo-1.2   then name=foo-1.2 and rebuild=
+#      # if bottle=foo-1.2^3 then name=foo-1.2 and rebuild=.3
+#      name=${bottle%^*}
+#      rebuild=${bottle#$name}
+#      rebuild=${rebuild:+.}${rebuild#^}
+#
+#      url=https://homebrew.bintray.com/bottles/$name.$BOTTLE_TAG.bottle$rebuild.tar.gz
+#      echo "Downloading $url..."
+#
+#      mkdir -p ~/Cellar
+#      curl -sS -L "$url" | gzip -d | tar x -C ~/Cellar
+#    done
+#
+#    # We don't have linker flags appropriate for linking against ar archives
+#    # at the moment. Ensure the dylibs are chosen by removing the archives.
+#    find ~/Cellar -name '*.a' -delete 2>/dev/null
+#
+#    # Link Homebrew bottles into a "/usr/local"-like environment in the home
+#    # directory because the real /usr/local is read-only.
+#    for pkg in ~/Cellar/*; do
+#      builtin pushd $pkg >/dev/null
+#      mkdir -p ~/opt
+#      ln -s * ~/opt/${pkg##*/}
+#      builtin popd >/dev/null
+#
+#      builtin pushd $pkg/* >/dev/null
+#      for config in $(find lib/cmake -type f 2>/dev/null); do
+#        sed -i '' -e s-@@HOMEBREW_PREFIX@@-$HOME- $config
+#      done
+#      for f in $(find bin include lib share -type d 2>/dev/null); do
+#        mkdir -p ~/"$f"
+#      done
+#      (
+#        IFS='
+#    '
+#        for f in $(find bin include lib share -type f 2>/dev/null); do
+#          ln -s "$f" ~/"$f"
+#        done
+#      )
+#      for f in $(find bin include lib share -type l 2>/dev/null); do
+#        cp "$f" ~/"$f"
+#      done
+#      builtin popd >/dev/null
+#    done
+#
+#    # Configure dylib install names.
+#    for dylib in $(find ~/Cellar -name '*.dylib' -type f 2>/dev/null); do
+#      #otool -L $dylib
+#      chmod +w $dylib
+#      install_name_tool -id $dylib $dylib
+#      for line in $(otool -L $dylib | grep @@HOMEBREW_PREFIX@@); do
+#        link=$(echo $line | awk '{ print $1 }')
+#        link=${link#@@HOMEBREW_PREFIX@@/}
+#        install_name_tool -change @@HOMEBREW_PREFIX@@/$link ~/$link $dylib
+#      done
+#      for line in $(otool -L $dylib | grep @@HOMEBREW_CELLAR@@); do
+#        link=$(echo $line | awk '{ print $1 }')
+#        link=${link#@@HOMEBREW_CELLAR@@/}
+#        install_name_tool -change @@HOMEBREW_CELLAR@@/$link ~/Cellar/$link $dylib
+#      done
+#      #otool -L $dylib
+#    done
+#
+#    export PATH=~/bin:"$PATH"
+#    export CFLAGS="-I$HOME/include $CFLAGS"
+#    export CXXFLAGS="-I$HOME/include $CXXFLAGS"
+#    export LDFLAGS="-L$HOME/lib $LDFLAGS"
+#    export CMAKE_PREFIX_PATH=~/lib/cmake${CMAKE_PREFIX_PATH:+;}"$CMAKE_PREFIX_PATH"
+#
+#    mkdir build
+#    builtin cd >/dev/null build
+#    cmake .. -DCMAKE_BUILD_TYPE=Debug $CMAKE_OPTS
+#    make -j `sysctl -n hw.ncpu`
+#    ./units
+#    )
 
 jobs:
   include:
   - name: 10.11 El Capitan null
     osx_image: xcode7.3
-    env:
-    - BOTTLE_TAG=el_capitan
-    - BOTTLES=cmake-3.12.2
-    <<: *script
-  - name: 10.11 El Capitan sdl2
-    osx_image: xcode7.3
-    env:
-    - BOTTLE_TAG=el_capitan
-    - BOTTLES='cmake-3.12.2 libmodplug-0.8.9.0 libogg-1.3.3 libvorbis-1.3.6 sdl2-2.0.8 sdl2_mixer-2.0.2'
-    - CMAKE_OPTS='-DAV_SDL2=On -DUSE_SDL2_PKGCONFIG=Off -DSDL2_LIBRARY_DIRS=$HOME/lib -DSDL2_LIBRARIES=SDL2 -DSDL2_mixer_LIBRARY_DIRS=$HOME/lib -DSDL2_mixer_LIBRARIES=SDL2_mixer'
-    <<: *script
-  - name: 10.15 Catalina null
-    osx_image: xcode12.2
-    <<: *script
-  - name: 10.15 Catalina sdl2
-    osx_image: xcode12.2
-    env:
-    - BOTTLE_TAG=catalina
-    - BOTTLES='libmodplug-0.8.9.0^1 libogg-1.3.4 libvorbis-1.3.7 sdl2-2.0.12 sdl2_mixer-2.0.4'
-    - CMAKE_OPTS='-DAV_SDL2=On -DUSE_SDL2_PKGCONFIG=Off -DSDL2_LIBRARY_DIRS=$HOME/lib -DSDL2_LIBRARIES=SDL2 -DSDL2_mixer_LIBRARY_DIRS=$HOME/lib -DSDL2_mixer_LIBRARIES=SDL2_mixer'
-    <<: *script
+    #env:
+    #- BOTTLE_TAG=el_capitan
+    #- BOTTLES=cmake-3.12.2
+    script:
+    - |
+      mkdir build
+      builtin cd >/dev/null build
+      cmake .. -DCMAKE_BUILD_TYPE=Debug $CMAKE_OPTS
+      make -j `sysctl -n hw.ncpu`
+      ./units
+#    <<: *script
+#  - name: 10.11 El Capitan sdl2
+#    osx_image: xcode7.3
+#    env:
+#    - BOTTLE_TAG=el_capitan
+#    - BOTTLES='cmake-3.12.2 libmodplug-0.8.9.0 libogg-1.3.3 libvorbis-1.3.6 sdl2-2.0.8 sdl2_mixer-2.0.2'
+#    - CMAKE_OPTS='-DAV_SDL2=On -DUSE_SDL2_PKGCONFIG=Off -DSDL2_LIBRARY_DIRS=$HOME/lib -DSDL2_LIBRARIES=SDL2 -DSDL2_mixer_LIBRARY_DIRS=$HOME/lib -DSDL2_mixer_LIBRARIES=SDL2_mixer'
+#    <<: *script
+#  - name: 10.15 Catalina null
+#    osx_image: xcode12.2
+#    <<: *script
+#  - name: 10.15 Catalina sdl2
+#    osx_image: xcode12.2
+#    env:
+#    - BOTTLE_TAG=catalina
+#    - BOTTLES='libmodplug-0.8.9.0^1 libogg-1.3.4 libvorbis-1.3.7 sdl2-2.0.12 sdl2_mixer-2.0.4'
+#    - CMAKE_OPTS='-DAV_SDL2=On -DUSE_SDL2_PKGCONFIG=Off -DSDL2_LIBRARY_DIRS=$HOME/lib -DSDL2_LIBRARIES=SDL2 -DSDL2_mixer_LIBRARY_DIRS=$HOME/lib -DSDL2_mixer_LIBRARIES=SDL2_mixer'
+#    <<: *script
